# Generated by Django 5.2.6 on 2025-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
