# Generated by Django 5.2.6 on 2025-09-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_dummy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothes', 'Clothes'), ('accessories', 'Accessories'), ('limited', 'Limited Edition')], default='shoes', max_length=50),
        ),
    ]
